{
 "title": "Real-time Monitoring Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Flask App Instance Matrix",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ALERTS{instance=\"localhost:5000\"}"
    }
   ]
  },
  {
   "title": "Alerts in Pending State",
   "type": "timeseries",
   "description": "Displays the CPU usage trends over time, helping to identify patterns and anomalies in CPU usage",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "ALERTS{alertstate=\"pending\"}"
    }
   ]
  },
  {
   "title": "Flask App Application Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "ALERTS{instance=\"localhost:5000\"}"
    }
   ]
  },
  {
   "title": "Alerts in Firing State",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "ALERTS{alertstate=\"firing\"}"
    }
   ]
  },
  {
   "title": "Unavailable Services",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "ALERTS{alertname=\"ServiceUnavailable\"}"
    }
   ]
  },
  {
   "title": "Flask App Job Matrix",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "ALERTS{job=\"flask_app\"}"
    }
   ]
  }
 ]
}