groups:
  - name: example
    rules:
      - alert: HighCPUUsage
        expr: 100 - (avg(irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 90
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU Usage Detected"
          description: "The CPU usage has exceeded 90% for more than 5 minutes."

      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemFree_bytes) / node_memory_MemTotal_bytes * 100 > 90
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High Memory Usage Detected"
          description: "The memory usage has exceeded 90% for more than 5 minutes."

      - alert: LowDiskSpace
        expr: (node_filesystem_size_bytes - node_filesystem_free_bytes) / node_filesystem_size_bytes * 100 < 10
        for: 15m
        labels:
          severity: critical
        annotations:
          summary: "Low Disk Space Detected"
          description: "The available disk space has fallen below 10% for more than 15 minutes."

      - alert: HighNetworkTraffic
        expr: sum(rate(node_network_receive_bytes_total[5m])) > 100e6
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High Network Traffic Detected"
          description: "The incoming network traffic has exceeded 100 Mbps for more than 10 minutes."

      - alert: ServiceUnavailable
        expr: up == 0
        labels:
          severity: critical
        annotations:
          summary: "Service Unavailable Detected"
          description: "The service is unavailable."

